version: "3.9"
services:
    python_backend:
        container_name: s3label_python_backend
        image: s3label_python_backend:latest
        build: 
            context: "backend"
            dockerfile: Dockerfile.python
        ports:
            - "5000:5000"
        volumes:
            - /home/s3label/s3label-storage:/home/ubuntu
        depends_on:
            - "postgresql_backend"
        network_mode: host
        # entrypoint: tail -F "wait"
    postgresql_backend:
        container_name: s3label_postgresql_backend
        image: postgres:latest
        ports:
            - "5432:5432"
        volumes:
            - ./backend/unit_test_data:/docker-entrypoint-initdb.d
            - ./postgres-data:/var/lib/postgresql/data
            - /home/s3label/s3label-storage:/home/ubuntu
        environment:
            - "POSTGRES_PASSWORD=thisispassword"
            - "POSTGRES_DB=s3_label_live"
    frontend:
        container_name: s3label_frontend
        image: s3label_frontend:latest
        build:
            context: "frontend/spa"
        ports:
            - "8080:8080"
        volumes:
            - /home/s3label/s3label-storage:/home/ubuntu
        network_mode: host