FROM postgres:latest

RUN createdb -h 127.0.0.1 -p 8999 -U ryanpg s3label

COPY . /home/backend
WORKDIR /home/backend

RUN psql -U ryanpg -d s3label -f unit_tests/create_db_tables.sql
RUN psql -U ryanpg -d s3label -f unit_tests/init_unit_test_data.sql

EXPOSE 8999
CMD ["postgres"]